name: create release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      OUTPUT_PATH: 'app/build/outputs/apk/release'
      KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
      KEYSTORE_ENC_KEY: ${{ secrets.KEYSTORE_ENC_KEY }}
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      KEYSTORE_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}
      KEYSTORE_ALIAS_PASSWORD: ${{ secrets.KEYSTORE_ALIAS_PASSWORD }}

    steps:
    - uses: actions/checkout@v2

    - name: set up jdk
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: decode keystore
      run: ./.github/scripts/decode_keystore.sh $KEYSTORE_BASE64

    - name: make gradlew executable
      run: chmod +x gradlew

    - name: assemble
      run: ./gradlew assembleRelease

    - name: current tag
      id: current_tag
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

    - name: rename apk
      run: mv "$OUTPUT_PATH/app-release.apk" "$OUTPUT_PATH/15-puzzle-${{ steps.current_tag.outputs.tag }}.apk"

    - name: release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "${{ env.OUTPUT_PATH }}/*.apk"
        prerelease: true
        token: ${{ secrets.GITHUB_TOKEN }}
