name: create-release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      APK_OUTPUT_PATH: 'app/build/outputs/apk/release'
      AAB_OUTPUT_PATH: 'app/build/outputs/bundle/release'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: decode keystore
      uses: italankin/android-keystore-decode-action@v1
      with:
        output_dir: 'app/keystore-release/'
        keystore_name: 'release.keystore'
        properties_name: 'release.properties'
        encoded_keystore: ${{ secrets.KEYSTORE_BASE64 }}
        keystore_password: ${{ secrets.KEYSTORE_PASSWORD }}
        key_alias: ${{ secrets.KEYSTORE_ALIAS }}
        key_alias_password: ${{ secrets.KEYSTORE_ALIAS_PASSWORD }}

    - name: make gradlew executable
      run: chmod +x gradlew

    - name: assemble
      run: ./gradlew assembleRelease bundleRelease

    - name: get current tag
      id: current_tag
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

    - name: rename artifacts
      run: >
        mv "$APK_OUTPUT_PATH/app-release.apk" "$APK_OUTPUT_PATH/15-puzzle-${{ steps.current_tag.outputs.tag }}.apk" &&
        mv "$AAB_OUTPUT_PATH/app-release.aab" "$AAB_OUTPUT_PATH/15-puzzle-${{ steps.current_tag.outputs.tag }}.aab"

    - name: create release
      uses: ncipollo/release-action@v1.12.0
      with:
        artifacts: "${{ env.APK_OUTPUT_PATH }}/*.apk"
        prerelease: true
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: upload aab
      uses: actions/upload-artifact@v3
      with:
        name: "15-puzzle-${{ steps.current_tag.outputs.tag }}.aab"
        path: "${{ env.AAB_OUTPUT_PATH }}/**"
        retention-days: 2
